// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/weather.proto

package edu.malens.grpc;

/**
 * Protobuf type {@code weatherproto.WeatherRequest}
 */
public  final class WeatherRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:weatherproto.WeatherRequest)
    WeatherRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeatherRequest.newBuilder() to construct.
  private WeatherRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeatherRequest() {
    city_ = "";
    date_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WeatherRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeatherRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              date_ = new java.util.ArrayList<edu.malens.grpc.Date>();
              mutable_bitField0_ |= 0x00000001;
            }
            date_.add(
                input.readMessage(edu.malens.grpc.Date.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        date_ = java.util.Collections.unmodifiableList(date_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.malens.grpc.WeatherProto.internal_static_weatherproto_WeatherRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.malens.grpc.WeatherProto.internal_static_weatherproto_WeatherRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.malens.grpc.WeatherRequest.class, edu.malens.grpc.WeatherRequest.Builder.class);
  }

  public static final int CITY_FIELD_NUMBER = 1;
  private volatile java.lang.Object city_;
  /**
   * <code>string city = 1;</code>
   * @return The city.
   */
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <code>string city = 1;</code>
   * @return The bytes for city.
   */
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATE_FIELD_NUMBER = 2;
  private java.util.List<edu.malens.grpc.Date> date_;
  /**
   * <code>repeated .weatherproto.Date date = 2;</code>
   */
  public java.util.List<edu.malens.grpc.Date> getDateList() {
    return date_;
  }
  /**
   * <code>repeated .weatherproto.Date date = 2;</code>
   */
  public java.util.List<? extends edu.malens.grpc.DateOrBuilder> 
      getDateOrBuilderList() {
    return date_;
  }
  /**
   * <code>repeated .weatherproto.Date date = 2;</code>
   */
  public int getDateCount() {
    return date_.size();
  }
  /**
   * <code>repeated .weatherproto.Date date = 2;</code>
   */
  public edu.malens.grpc.Date getDate(int index) {
    return date_.get(index);
  }
  /**
   * <code>repeated .weatherproto.Date date = 2;</code>
   */
  public edu.malens.grpc.DateOrBuilder getDateOrBuilder(
      int index) {
    return date_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, city_);
    }
    for (int i = 0; i < date_.size(); i++) {
      output.writeMessage(2, date_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, city_);
    }
    for (int i = 0; i < date_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, date_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.malens.grpc.WeatherRequest)) {
      return super.equals(obj);
    }
    edu.malens.grpc.WeatherRequest other = (edu.malens.grpc.WeatherRequest) obj;

    if (!getCity()
        .equals(other.getCity())) return false;
    if (!getDateList()
        .equals(other.getDateList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    if (getDateCount() > 0) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDateList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.malens.grpc.WeatherRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.malens.grpc.WeatherRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.malens.grpc.WeatherRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.malens.grpc.WeatherRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.malens.grpc.WeatherRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.malens.grpc.WeatherRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.malens.grpc.WeatherRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.malens.grpc.WeatherRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.malens.grpc.WeatherRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.malens.grpc.WeatherRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.malens.grpc.WeatherRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.malens.grpc.WeatherRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.malens.grpc.WeatherRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code weatherproto.WeatherRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:weatherproto.WeatherRequest)
      edu.malens.grpc.WeatherRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.malens.grpc.WeatherProto.internal_static_weatherproto_WeatherRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.malens.grpc.WeatherProto.internal_static_weatherproto_WeatherRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.malens.grpc.WeatherRequest.class, edu.malens.grpc.WeatherRequest.Builder.class);
    }

    // Construct using edu.malens.grpc.WeatherRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDateFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      city_ = "";

      if (dateBuilder_ == null) {
        date_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dateBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.malens.grpc.WeatherProto.internal_static_weatherproto_WeatherRequest_descriptor;
    }

    @java.lang.Override
    public edu.malens.grpc.WeatherRequest getDefaultInstanceForType() {
      return edu.malens.grpc.WeatherRequest.getDefaultInstance();
    }

    @java.lang.Override
    public edu.malens.grpc.WeatherRequest build() {
      edu.malens.grpc.WeatherRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.malens.grpc.WeatherRequest buildPartial() {
      edu.malens.grpc.WeatherRequest result = new edu.malens.grpc.WeatherRequest(this);
      int from_bitField0_ = bitField0_;
      result.city_ = city_;
      if (dateBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          date_ = java.util.Collections.unmodifiableList(date_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.date_ = date_;
      } else {
        result.date_ = dateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.malens.grpc.WeatherRequest) {
        return mergeFrom((edu.malens.grpc.WeatherRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.malens.grpc.WeatherRequest other) {
      if (other == edu.malens.grpc.WeatherRequest.getDefaultInstance()) return this;
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (dateBuilder_ == null) {
        if (!other.date_.isEmpty()) {
          if (date_.isEmpty()) {
            date_ = other.date_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDateIsMutable();
            date_.addAll(other.date_);
          }
          onChanged();
        }
      } else {
        if (!other.date_.isEmpty()) {
          if (dateBuilder_.isEmpty()) {
            dateBuilder_.dispose();
            dateBuilder_ = null;
            date_ = other.date_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dateBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDateFieldBuilder() : null;
          } else {
            dateBuilder_.addAllMessages(other.date_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.malens.grpc.WeatherRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.malens.grpc.WeatherRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object city_ = "";
    /**
     * <code>string city = 1;</code>
     * @return The city.
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string city = 1;</code>
     * @return The bytes for city.
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string city = 1;</code>
     * @param value The city to set.
     * @return This builder for chaining.
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string city = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <code>string city = 1;</code>
     * @param value The bytes for city to set.
     * @return This builder for chaining.
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private java.util.List<edu.malens.grpc.Date> date_ =
      java.util.Collections.emptyList();
    private void ensureDateIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        date_ = new java.util.ArrayList<edu.malens.grpc.Date>(date_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.malens.grpc.Date, edu.malens.grpc.Date.Builder, edu.malens.grpc.DateOrBuilder> dateBuilder_;

    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public java.util.List<edu.malens.grpc.Date> getDateList() {
      if (dateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(date_);
      } else {
        return dateBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public int getDateCount() {
      if (dateBuilder_ == null) {
        return date_.size();
      } else {
        return dateBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public edu.malens.grpc.Date getDate(int index) {
      if (dateBuilder_ == null) {
        return date_.get(index);
      } else {
        return dateBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public Builder setDate(
        int index, edu.malens.grpc.Date value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDateIsMutable();
        date_.set(index, value);
        onChanged();
      } else {
        dateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public Builder setDate(
        int index, edu.malens.grpc.Date.Builder builderForValue) {
      if (dateBuilder_ == null) {
        ensureDateIsMutable();
        date_.set(index, builderForValue.build());
        onChanged();
      } else {
        dateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public Builder addDate(edu.malens.grpc.Date value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDateIsMutable();
        date_.add(value);
        onChanged();
      } else {
        dateBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public Builder addDate(
        int index, edu.malens.grpc.Date value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDateIsMutable();
        date_.add(index, value);
        onChanged();
      } else {
        dateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public Builder addDate(
        edu.malens.grpc.Date.Builder builderForValue) {
      if (dateBuilder_ == null) {
        ensureDateIsMutable();
        date_.add(builderForValue.build());
        onChanged();
      } else {
        dateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public Builder addDate(
        int index, edu.malens.grpc.Date.Builder builderForValue) {
      if (dateBuilder_ == null) {
        ensureDateIsMutable();
        date_.add(index, builderForValue.build());
        onChanged();
      } else {
        dateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public Builder addAllDate(
        java.lang.Iterable<? extends edu.malens.grpc.Date> values) {
      if (dateBuilder_ == null) {
        ensureDateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, date_);
        onChanged();
      } else {
        dateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public Builder clearDate() {
      if (dateBuilder_ == null) {
        date_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public Builder removeDate(int index) {
      if (dateBuilder_ == null) {
        ensureDateIsMutable();
        date_.remove(index);
        onChanged();
      } else {
        dateBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public edu.malens.grpc.Date.Builder getDateBuilder(
        int index) {
      return getDateFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public edu.malens.grpc.DateOrBuilder getDateOrBuilder(
        int index) {
      if (dateBuilder_ == null) {
        return date_.get(index);  } else {
        return dateBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public java.util.List<? extends edu.malens.grpc.DateOrBuilder> 
         getDateOrBuilderList() {
      if (dateBuilder_ != null) {
        return dateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(date_);
      }
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public edu.malens.grpc.Date.Builder addDateBuilder() {
      return getDateFieldBuilder().addBuilder(
          edu.malens.grpc.Date.getDefaultInstance());
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public edu.malens.grpc.Date.Builder addDateBuilder(
        int index) {
      return getDateFieldBuilder().addBuilder(
          index, edu.malens.grpc.Date.getDefaultInstance());
    }
    /**
     * <code>repeated .weatherproto.Date date = 2;</code>
     */
    public java.util.List<edu.malens.grpc.Date.Builder> 
         getDateBuilderList() {
      return getDateFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.malens.grpc.Date, edu.malens.grpc.Date.Builder, edu.malens.grpc.DateOrBuilder> 
        getDateFieldBuilder() {
      if (dateBuilder_ == null) {
        dateBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.malens.grpc.Date, edu.malens.grpc.Date.Builder, edu.malens.grpc.DateOrBuilder>(
                date_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        date_ = null;
      }
      return dateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:weatherproto.WeatherRequest)
  }

  // @@protoc_insertion_point(class_scope:weatherproto.WeatherRequest)
  private static final edu.malens.grpc.WeatherRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.malens.grpc.WeatherRequest();
  }

  public static edu.malens.grpc.WeatherRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeatherRequest>
      PARSER = new com.google.protobuf.AbstractParser<WeatherRequest>() {
    @java.lang.Override
    public WeatherRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WeatherRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeatherRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeatherRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.malens.grpc.WeatherRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

