// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/weather.proto

package edu.malens.grpc;

/**
 * Protobuf type {@code weatherproto.WeatherDay}
 */
public  final class WeatherDay extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:weatherproto.WeatherDay)
    WeatherDayOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeatherDay.newBuilder() to construct.
  private WeatherDay(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeatherDay() {
    state_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WeatherDay();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeatherDay(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            edu.malens.grpc.Date.Builder subBuilder = null;
            if (date_ != null) {
              subBuilder = date_.toBuilder();
            }
            date_ = input.readMessage(edu.malens.grpc.Date.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(date_);
              date_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            state_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.malens.grpc.WeatherProto.internal_static_weatherproto_WeatherDay_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.malens.grpc.WeatherProto.internal_static_weatherproto_WeatherDay_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.malens.grpc.WeatherDay.class, edu.malens.grpc.WeatherDay.Builder.class);
  }

  public static final int DATE_FIELD_NUMBER = 1;
  private edu.malens.grpc.Date date_;
  /**
   * <code>.weatherproto.Date date = 1;</code>
   * @return Whether the date field is set.
   */
  public boolean hasDate() {
    return date_ != null;
  }
  /**
   * <code>.weatherproto.Date date = 1;</code>
   * @return The date.
   */
  public edu.malens.grpc.Date getDate() {
    return date_ == null ? edu.malens.grpc.Date.getDefaultInstance() : date_;
  }
  /**
   * <code>.weatherproto.Date date = 1;</code>
   */
  public edu.malens.grpc.DateOrBuilder getDateOrBuilder() {
    return getDate();
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private int state_;
  /**
   * <code>.weatherproto.WeatherState state = 2;</code>
   * @return The enum numeric value on the wire for state.
   */
  public int getStateValue() {
    return state_;
  }
  /**
   * <code>.weatherproto.WeatherState state = 2;</code>
   * @return The state.
   */
  public edu.malens.grpc.WeatherState getState() {
    @SuppressWarnings("deprecation")
    edu.malens.grpc.WeatherState result = edu.malens.grpc.WeatherState.valueOf(state_);
    return result == null ? edu.malens.grpc.WeatherState.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (date_ != null) {
      output.writeMessage(1, getDate());
    }
    if (state_ != edu.malens.grpc.WeatherState.CLEAR.getNumber()) {
      output.writeEnum(2, state_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (date_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDate());
    }
    if (state_ != edu.malens.grpc.WeatherState.CLEAR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, state_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.malens.grpc.WeatherDay)) {
      return super.equals(obj);
    }
    edu.malens.grpc.WeatherDay other = (edu.malens.grpc.WeatherDay) obj;

    if (hasDate() != other.hasDate()) return false;
    if (hasDate()) {
      if (!getDate()
          .equals(other.getDate())) return false;
    }
    if (state_ != other.state_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDate()) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
    }
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.malens.grpc.WeatherDay parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.malens.grpc.WeatherDay parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.malens.grpc.WeatherDay parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.malens.grpc.WeatherDay parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.malens.grpc.WeatherDay parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.malens.grpc.WeatherDay parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.malens.grpc.WeatherDay parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.malens.grpc.WeatherDay parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.malens.grpc.WeatherDay parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.malens.grpc.WeatherDay parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.malens.grpc.WeatherDay parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.malens.grpc.WeatherDay parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.malens.grpc.WeatherDay prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code weatherproto.WeatherDay}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:weatherproto.WeatherDay)
      edu.malens.grpc.WeatherDayOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.malens.grpc.WeatherProto.internal_static_weatherproto_WeatherDay_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.malens.grpc.WeatherProto.internal_static_weatherproto_WeatherDay_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.malens.grpc.WeatherDay.class, edu.malens.grpc.WeatherDay.Builder.class);
    }

    // Construct using edu.malens.grpc.WeatherDay.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dateBuilder_ == null) {
        date_ = null;
      } else {
        date_ = null;
        dateBuilder_ = null;
      }
      state_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.malens.grpc.WeatherProto.internal_static_weatherproto_WeatherDay_descriptor;
    }

    @java.lang.Override
    public edu.malens.grpc.WeatherDay getDefaultInstanceForType() {
      return edu.malens.grpc.WeatherDay.getDefaultInstance();
    }

    @java.lang.Override
    public edu.malens.grpc.WeatherDay build() {
      edu.malens.grpc.WeatherDay result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.malens.grpc.WeatherDay buildPartial() {
      edu.malens.grpc.WeatherDay result = new edu.malens.grpc.WeatherDay(this);
      if (dateBuilder_ == null) {
        result.date_ = date_;
      } else {
        result.date_ = dateBuilder_.build();
      }
      result.state_ = state_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.malens.grpc.WeatherDay) {
        return mergeFrom((edu.malens.grpc.WeatherDay)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.malens.grpc.WeatherDay other) {
      if (other == edu.malens.grpc.WeatherDay.getDefaultInstance()) return this;
      if (other.hasDate()) {
        mergeDate(other.getDate());
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.malens.grpc.WeatherDay parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.malens.grpc.WeatherDay) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private edu.malens.grpc.Date date_;
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.malens.grpc.Date, edu.malens.grpc.Date.Builder, edu.malens.grpc.DateOrBuilder> dateBuilder_;
    /**
     * <code>.weatherproto.Date date = 1;</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return dateBuilder_ != null || date_ != null;
    }
    /**
     * <code>.weatherproto.Date date = 1;</code>
     * @return The date.
     */
    public edu.malens.grpc.Date getDate() {
      if (dateBuilder_ == null) {
        return date_ == null ? edu.malens.grpc.Date.getDefaultInstance() : date_;
      } else {
        return dateBuilder_.getMessage();
      }
    }
    /**
     * <code>.weatherproto.Date date = 1;</code>
     */
    public Builder setDate(edu.malens.grpc.Date value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        date_ = value;
        onChanged();
      } else {
        dateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.weatherproto.Date date = 1;</code>
     */
    public Builder setDate(
        edu.malens.grpc.Date.Builder builderForValue) {
      if (dateBuilder_ == null) {
        date_ = builderForValue.build();
        onChanged();
      } else {
        dateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.weatherproto.Date date = 1;</code>
     */
    public Builder mergeDate(edu.malens.grpc.Date value) {
      if (dateBuilder_ == null) {
        if (date_ != null) {
          date_ =
            edu.malens.grpc.Date.newBuilder(date_).mergeFrom(value).buildPartial();
        } else {
          date_ = value;
        }
        onChanged();
      } else {
        dateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.weatherproto.Date date = 1;</code>
     */
    public Builder clearDate() {
      if (dateBuilder_ == null) {
        date_ = null;
        onChanged();
      } else {
        date_ = null;
        dateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.weatherproto.Date date = 1;</code>
     */
    public edu.malens.grpc.Date.Builder getDateBuilder() {
      
      onChanged();
      return getDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.weatherproto.Date date = 1;</code>
     */
    public edu.malens.grpc.DateOrBuilder getDateOrBuilder() {
      if (dateBuilder_ != null) {
        return dateBuilder_.getMessageOrBuilder();
      } else {
        return date_ == null ?
            edu.malens.grpc.Date.getDefaultInstance() : date_;
      }
    }
    /**
     * <code>.weatherproto.Date date = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.malens.grpc.Date, edu.malens.grpc.Date.Builder, edu.malens.grpc.DateOrBuilder> 
        getDateFieldBuilder() {
      if (dateBuilder_ == null) {
        dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            edu.malens.grpc.Date, edu.malens.grpc.Date.Builder, edu.malens.grpc.DateOrBuilder>(
                getDate(),
                getParentForChildren(),
                isClean());
        date_ = null;
      }
      return dateBuilder_;
    }

    private int state_ = 0;
    /**
     * <code>.weatherproto.WeatherState state = 2;</code>
     * @return The enum numeric value on the wire for state.
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <code>.weatherproto.WeatherState state = 2;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.weatherproto.WeatherState state = 2;</code>
     * @return The state.
     */
    public edu.malens.grpc.WeatherState getState() {
      @SuppressWarnings("deprecation")
      edu.malens.grpc.WeatherState result = edu.malens.grpc.WeatherState.valueOf(state_);
      return result == null ? edu.malens.grpc.WeatherState.UNRECOGNIZED : result;
    }
    /**
     * <code>.weatherproto.WeatherState state = 2;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(edu.malens.grpc.WeatherState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.weatherproto.WeatherState state = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      
      state_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:weatherproto.WeatherDay)
  }

  // @@protoc_insertion_point(class_scope:weatherproto.WeatherDay)
  private static final edu.malens.grpc.WeatherDay DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.malens.grpc.WeatherDay();
  }

  public static edu.malens.grpc.WeatherDay getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeatherDay>
      PARSER = new com.google.protobuf.AbstractParser<WeatherDay>() {
    @java.lang.Override
    public WeatherDay parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WeatherDay(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeatherDay> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeatherDay> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.malens.grpc.WeatherDay getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

